# デプロイしたいディレクトリの設定
[build]
  publish = "/dist"

# 本番環境のビルドコマンド
[context.production]
  command = "yarn && yarn prod"

# ステージング環境のビルドコマンド
[context.staging]
  command = "yarn && yarn stg"

# SPA用の設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200